# Generated by Django 2.1.15 on 2021-02-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(blank=True, max_length=14)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('born_date', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'client',
            },
        ),
    ]
