# Generated by Django 2.1.15 on 2021-02-12 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryOfferModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_call', models.DateField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_history_offer', to='client.ClientModel')),
            ],
            options={
                'db_table': 'history_offers',
            },
        ),
        migrations.CreateModel(
            name='OfferModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_id', models.IntegerField(blank=True)),
                ('partner_name', models.CharField(blank=True, max_length=150)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('installments', models.IntegerField(blank=True)),
                ('tax_rate_percent_montly', models.FloatField(blank=True)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('history_offers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_offers_fk', to='offers.HistoryOfferModel')),
            ],
            options={
                'db_table': 'offers',
            },
        ),
    ]
