# Generated by Django 2.1.15 on 2021-02-12 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_send', models.DateField()),
                ('proposal_id', models.PositiveIntegerField(blank=True)),
                ('message', models.CharField(blank=True, max_length=200)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposal_client', to='client.ClientModel')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposal_offer', to='offers.OfferModel')),
            ],
            options={
                'db_table': 'proposal',
            },
        ),
    ]
